### ISSUE TITLE
Grid item is not updated after editing the item

### ISSUE THREAD

**Issue by Wnt** [mvysny/beverage-buddy-vok#3]
Steps to reproduce:
1. click edit on a item
2. edit e.g. date or 'Times tasted'
3. click save
4. grid item should show the new values
what happens instead:
4. grid still shows old values. after a page refresh the new values are shown.

Tested using Firefox with the version deployed to https://beverage-buddy-vok.herokuapp.com

**Comment by mvysny** [comment]
Thanks! I believe it's a bug in the Vaadin Grid component, and has been reported here: https://github.com/vaadin/vaadin-grid-flow/issues/175
